services:
  phpipam-web:
    image: phpipam/phpipam-www:latest
    ports:
      - "80:80"
    environment:
      - TZ=${TZ:-America/Chicago} # Define o fuso horário, padrão America/Chicago
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=${IPAM_DB_PASSWORD} # Senha do usuário do banco de dados PHPIPAM (definida no .env)
      - IPAM_DATABASE_WEBHOST=% # Permite conexões da web de qualquer host (padrão PHPIPAM)
    restart: always
    volumes:
      - phpipam-logo:/phpipam/css/images/logo # Volume para logo customizado
      - phpipam-ca:/usr/local/share/ca-certificates:ro # Volume para certificados CA (somente leitura)
    depends_on:
      phpipam-mariadb:
        condition: service_healthy # Espera o MariaDB estar saudável

  phpipam-cron:
    image: phpipam/phpipam-cron:latest
    environment:
      - TZ=${TZ:-Europe/London} # Define o fuso horário, padrão Europe/London
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=${IPAM_DB_PASSWORD} # Senha do usuário do banco de dados PHPIPAM (definida no .env)
      - SCAN_INTERVAL=${SCAN_INTERVAL:-1h} # Intervalo de scan (padrão 1 hora)
    restart: always
    volumes:
      - phpipam-ca:/usr/local/share/ca-certificates:ro # Volume para certificados CA (somente leitura)
    depends_on:
      phpipam-mariadb:
        condition: service_healthy # Espera o MariaDB estar saudável

  phpipam-mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} # Senha root do MariaDB (definida no .env)
      # - MYSQL_DATABASE=phpipam # Opcional: Cria o banco de dados na inicialização
      # - MYSQL_USER=phpipam # Opcional: Cria o usuário na inicialização
      # - MYSQL_PASSWORD=${IPAM_DB_PASSWORD} # Opcional: Define a senha do usuário na inicialização
    restart: always
    volumes:
      - phpipam-db-data:/var/lib/mysql # Volume para os dados do MariaDB
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  phpipam-db-data:
  phpipam-logo:
  phpipam-ca:
